version: "3"

services:

  accounts:
    image: aniketrathore/pycraft-accounts:1.1
    ports:
      - 8000
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  nginx:
    image: aniketrathore/pycraft-nginx:latest
    ports:
      - 80:80
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 15s
      restart_policy:
        condition: on-failure
